on:
  workflow_call:
    outputs:
      pnpm-store-path:
        description: "The path to the pnpm store"
        value: ${{ jobs.cache_dependencies.outputs.pnpm-store-path }}

jobs:
  cache_dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    outputs:
      pnpm-store-path: ${{ steps.pnpm-store-path.outputs.store-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Get pnpm store path
        id: pnpm-store-path
        run: echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store-path.outputs.store-path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Restore dependencies
        run: pnpm install --frozen-lockfile
